### ISSUE TITLE
Babel option resolveModuleSource not working

### ISSUE THREAD

**Issue by RobertCZ** [icecreamliker/requirejs-babel-plugin#11]
Babel option resolveModuleSource to insert es6! prefix to imported dependencies is not working because deep clone of babel config with JSON stringify/parse will remove functions from options. Quick fix would be something like

```
                babelOptions = JSON.parse(JSON.stringify(config.babel));
                babelOptions.resolveModuleSource = config.babel.resolveModuleSource
```

See also issue https://github.com/mikach/requirejs-babel/issues/26

**Comment by icecreamliker** [comment]
can you submit a PR, I'll merge it as soon as possible.
thank you.

**Comment by RobertCZ** [comment]
submitted

**Comment by icecreamliker** [comment]
Done.
Bump version to 0.5.0 on npm.
thank you.
