### ISSUE TITLE
How to use require.config({paths:{...}}) with this plugin?

### ISSUE THREAD

**Issue by Muzietto** [icecreamliker/requirejs-babel-plugin#13]
I am transpiling ES6 files using Gulp to activate Babel (with plugin 'transform-es2015-modules-amd').
I am unable to specify logical paths for requirejs, for example:

```
require.config({
  paths: {
    'react': '../lib/react.min.js',
    'react-dom': '../lib/react-dom.min.js',
  },
})
```
I am hoping this plugin can help me to specify these requirejs options into the ES5 files produced by Babel.
Where _exactly_ should I put the config info?

If I try naively to put it at the start of the first ES6 file, Babel moves the require.config instruction inside the `define` block, whereas I need it to remain outside.

**Comment by icecreamliker** [comment]
I am sorry, I can't help any more for I've used webpack for a long time.
If possible, you can have a try with webpack which is a good tool.
