### ISSUE TITLE
Deleting fileExtension from the configuration will remove it from subsequent requires

### ISSUE THREAD

**Issue by esbenp** [icecreamliker/requirejs-babel-plugin#2]
When removing fileExtension here https://github.com/icecreamliker/requirejs-babel-plugin/blob/master/es6.js#L54 you effectively remove it from the configuration object. Therefore if you use `.jsx` as fileExtension only the first require will actually be transformed. On subsequent requires the option is missing and will be interpreted as normal `.js`

I made a PR #1

**Comment by icecreamliker** [comment]
close #1
