### ISSUE TITLE
Support for the empty path setting in requirejs

### ISSUE THREAD

**Issue by peternorr** [icecreamliker/requirejs-babel-plugin#5]
Hi,

Can you add support for the "empty:" path?  Take a look at the requirejs text plugin for example...

https://github.com/requirejs/text/blob/master/text.js line 197- 200

Thanks!

**Comment by icecreamliker** [comment]
Hi, you can submit a PR, and I'll merge it asap!

**Comment by peternorr** [comment]
Can you add me as a contributor?

i tried pushing my branch...

Hi peternorr! You've successfully authenticated, but GitHub does not
provide shell access.

$  git push --set-upstream origin empty-path-fix

ERROR: Permission to icecreamliker/requirejs-babel-plugin.git denied to
peternorr.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

**Comment by icecreamliker** [comment]
Sry for missing this notification.
I guess probably you don't know how to contribute the PR.
So here is the tips:
1. fork this project
2. clone your own project, and make the change.
3. push the patch to your own upstream
4. request PR

for more information, you can read the github guide.

**Comment by peternorr** [comment]
Awesome. Sorry for newbie question!

**Comment by peternorr** [comment]
i see the merge to master, thanks!

How do we bump it to next version tag?

**Comment by icecreamliker** [comment]
I've bumped version to 0.2.0, plz check it out.
