### ISSUE TITLE
Babel6 source maps incorrect when nested

### ISSUE THREAD

**Issue by DanDeMicco** [icecreamliker/requirejs-babel-plugin#7]
Hi,

Facing an issue with this plugin regarding source maps. I am not sure if this is a babel-core issue or what but figured I would start here.

In my require config I am importing babel like so:

```
'es6': "libs/node_modules/requirejs-babel-plugin/es6",
'babel': "libs/node_modules/babel-standalone/babel"
```

When I require es6!my_module_name it works correctly and a source map is generated. However if my_module_name has dependencies such as

```
define([
'backbone',
'text!app/template.html',
'es6!app/dep1',
'es6!app/dep2',
'es6!app/dep3',
'webui-popover'
], function(Backbone, template, dep1, dep2, dep3, webuiPopover) 
```

(and maybe dep1, 2, or 3 has the same sort of structure) 

The source map reported by chrome will be the incorrect name. For example, if in dep1 I have a console.log('hi'); chrome will say the console.log is coming from dep3 even though it should be dep1. I have noticed if I remove dep3 from the define, the above statement will then then say the console.log is coming from dep2.

Should this be working?

Let me know if something is unclear. If needed I can try and put together a sample

**Comment by DanDeMicco** [comment]
Debugged the source and found the sourceFileName was getting the same value multiple times (dep3 in above example). Deep cloning the config object seems to solve it

**Comment by icecreamliker** [comment]
I've replied to your PR, submit a new PR, and I'll merge it as soon as possible
